### ISSUE TITLE
V3 Tracking Bug

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#725]
This is a breakdown of the work in V3. This can and should be altered as work is realised if it's regarded as a core piece of work for V3.

I've done my best to break this down into sections of related work.

## Logging and Error Messages
Size has been a problem and one area where we could be smarter is logging messages to the console as well as logging text in error messages.

There have been a few suggestions but would be good someone to research and firm up a proposal with reasons for and against techniques:

**Research Tasks**
- [x] Errors use codes on prod and messages on dev. Logs are largely stripped.

**Actionable Tasks**
- [x] Create WorkboxError Class in workbox-core that extends Error and ensure it reads clearly as a WorkboxError in the console
- [x] Move LogHelper over to workbox-core and add tests for groups etc (I suspect the API could be tidied up)
- [x] Add a way for developers to set a log level and figure out how this should apply to a developer filter.
- [x] Write up article on how to filter logs by log level and custom filter plus any extra details related to the research above.

## Building / Releasing / Deploying [@gauntface]
Historically things have been a bit shaky in terms of how we build, package and release everything and there is some vital work we can do here and some *optional* work.

**Actionable / Required Tasks**
- [x] Figure out a good structure for release code on NPM.
    - [x] What is the name and location of the browser bundle file? `build/browser` and `build/module`.
    - [x] What is the location of the default ES2015 module file? It's just index.mjs. This is moved for the final build so versioning can be done as part of the release process.
    - [x] What is the location of additional classes, does it feel natural to use with ES2015 imports? Everything is exported at the top level.
    - [x] Should we minify the NPM module code (i.e. should we strip out the comments etc)? No it's staying as is - expect developers to do this themselves.
- [x] Add lerna back in to V3
    - [x] Should be able to use lerna bootstrap without concurrency flag being needed (We had a bad dependency chain before).
    - [x] Make use of prepublish to ensure any build steps are performed during lerna boostrap (We shouldn't be doing any building in the gulp file to make lerna work)
- [x] How do we upload the files from the builds to CDN?
    - [x] What should the URL structure be for the CDN releases (prod vs dev, modules, versions)?
    - [x] How should the files be published to the CDN?
- [x] How do publish the modules as Zips on Github?
- [x] Can we offer the zips as part of the workbox-cli to download them?
- [x] Write up article that covers how modules are released and usage of each (i.e. ZIP, NPM bundles, NPM ES2015 modules, CLI). [Here in Wiki](https://github.com/GoogleChrome/workbox/wiki/V3-:-ES2015-Modules-&-Browser-Bundles.)

**Optional Tasks**
- [x] Is there anything that can be done to simplify the release process? Lerna and Rollup is a bit easier although still doing an unusual dance to get lerna versioning working.

## Cache Naming [@gauntface]

- [x] [Proposal](https://github.com/GoogleChrome/workbox/issues/800)
- [x] Figure out where cache names are used and how.
- [x] Figure out where cache names can be altered by developers.
- [x] Figure out a cleaner way for modules to get the cache name to use that's also easy for developers to reason why.
- [x] Write a document explaining cache naming for Workboxjs.org

## Plugins

- [x] Research which feels more natural / preferred by developers: `google.workbox.plugins.<PluginName>` vs `google.workbox.<ModuleName>.<PluginName>`
- [x] Find a way to expose a "plugin" interface in JSDocs

## Docs

- [X] How to add content to specific modules without it needing to be in source code. Web Fundamentals should make this trivial.

## Testing

- [x] Add better support for bundling along side more traditional browser, node and sw tests (@std/esm + service-worker-mocks === <3)

## workbox-core

- [x] Default Export should be an API to set up shared logic (cache name, log level).
- [x] Ensure logs and errors are useful and meaningful
- [x] Write module guide on WebFundamentals
- [x] Get API reviewed by someone else
- [x] Minimal demo

## workbox-precaching

- [x] Default Export should offer precaching with single function call `precache`
- [x] Update API to match proposal
- [x] Move over any `workbox-sw` into the `workbox-precaching` default instance
- [x] Ensure logs and errors are useful and meaningful
- [x] Write module guide on WebFundamentals
- [x] Get API reviewed by someone else
- [x] Minimal demo

## workbox-routing

- [x] Default export should offer routing with registerRoute* calls.
- [x] Update API to match proposal
- [x] Move over any `workbox-sw` functionality into the `workbox-routing` default instance
- [x] Ensure logs and errors are useful and meaningful
    - [x] Can you follow a single route from fetch event through to respondWith()?
- [x] Write module guide on WebFundamentals
- [x] Get API reviewed by someone else
- [x] Minimal demo

## workbox-runtime-caching

- [x] No default export.
- [x] Move request wrapper into static utility functions and make them part of `workbox-core`
- [x] Moving cache naming stuff in `workbox-core` along with any Cache Naming changes
- [x] Update API to match proposal
- [x] Move over any `workbox-sw` functionality into the `workbox-strategies`
- [x] Ensure logs and errors are useful and meaningful
    - [x] Can you follow a single route from fetch event through to respondWith()?
- [x] Write module guide on WebFundamentals
- [x] Get API reviewed by someone else
- [x] Minimal demo

## workbox-background-sync

- [x] No default export.
- [x] Update API to work with new structure
- [ ] Ensure logs and errors are useful and meaningful
- [x] Write module guide on WebFundamentals
- [ ] Get API reviewed by someone else
- [ ] Minimal demo

## workbox-broadcast-cache-update

- [x] No default export.
- [x] Update API to work with new structure
- [x] Update to match proposal
- [x] Ensure logs and errors are useful and meaningful
- [x] Write module guide on WebFundamentals
- [ ] Get API reviewed by someone else
- [x] Minimal demo

## workbox-cache-expiration

- [x] No default export.
- [x] Update API to work with new structure
- [x] Ensure logs and errors are useful and meaningful
- [x] Write module guide on WebFundamentals
- [x] Get API reviewed by someone else
- [x] Minimal demo

## workbox-cacheable-response

- [x] No default export.
- [x] Update API to work with new structure
- [x] Ensure logs and errors are useful and meaningful
- [x] Write module guide on WebFundamentals
- [ ] Get API reviewed by someone else
- [x] Minimal demo

## workbox-google-analytics

- [x] Default export should be something that will handle offline analytics
- [ ] Update API to work with new structure
- [ ] Ensure logs and errors are useful and meaningful
- [ ] **Optional**: Is there any ways to make it more standalone?
- [ ] Write module guide on WebFundamentals
- [ ] Get API reviewed by someone else
- [ ] Minimal demo

## workbox-sw

- [X] Default export should allow dev vs prod mode and manage loading of Workbox modules
- [X] Update the API to match v3
- [X] Update the API to work with new structure
- [X] Ensure logs and errors are useful and meaningful
- [x] Write module guide on WebFundamentals
- [x] Get API reviewed by someone else
- [X] Minimal demo

## workbox-build

- [x] Switch to CDN by default
- [x] Include option to not use CDN and copy files over
- [x] Update API to implement v3 proposal
- [x] Refactor interface so that "primary" inject/generate methods are separated from the utility methods that just work on the manifest.
- [x] Has method to copy files from various node_modules into project.
- [x] Write module guide on WebFundamentals
- [ ] Get API reviewed by someone else
- [ ] Minimal demo

## workbox-cli

- [x] Ensure config file errors when an [invalid / wrong file is supplied](https://github.com/GoogleChrome/workbox/issues/843)

## workbox-webpack-plugin

- [x] Switch to CDN by default
- [x] Include option to not use CDN and copy files over
- [x] Update API to implement v3 proposal
- [x] Use compilation assets to generate a manifest (instead of globPatterns)
- [x] Allow user to specify chunks to be used when creating the manifest
- [x] Generate service worker “in-memory” and make webpack responsible for writing to file system
- [ ] Support sw-precache config in workbox-webpack plugin (runtime-caching? drop staticFileIgnores in favor of “chunks” api)
- [ ] Write module guide on WebFundamentals
- [ ] Get API reviewed by someone else
- [ ] Minimal demo

## [TBD] workbox-range-request

- [ ] No default export.
- [ ] Update for new structure if released......
- [ ] Write module guide on WebFundamentals
- [ ] Get API reviewed by someone else
- [ ] Minimal demo

## Extras / Optional
- [x] Add a pr-bot plugin that will block a PR on a max size of 10KB for workbox-core, workbox-routing, workbox-precaching in prod builds.
- [x] Add some integration tests to enforce any common features across modules (i.e. namespace requirements, folder name consistencies, Assert is stripped in all prod builds etc).

**Comment by addyosmani** [comment]
First, this is excellent. Thanks for taking the time to put this together, @gauntface 👍 

> There have been a few suggestions but would be good someone to research and firm up a proposal with reasons for and against techniques

Another research task could be estimating what the **potential** savings of getting a better handle on logging in our dev vs prod builds might be. extreme: If we were to strip out _all_ logging, what do we save? 1%? 10%? of the bundle size.

> Figure out a good structure for release code on NPM.

Super important. Minifying npm module code has been a contentious topic in the community and I don't think anyone has quite settled on the best path forward here. I believe `lodash-es` just ships raw ESM and defers any further optimisation to the consumer.

> How do publish the modules as Zips on Github?

When I've done this for projects (inefficient as it probably was), I would just grab the GitHub generated zipfile of the latest tag and drop it into the release binaries section via manual upload. How much we invest in this step will possibly relate to how many folks we see using zips from the releases page.

> Add a pr-bot plugin that will block a PR on a max size of 10KB for workbox-core, workbox-routing, workbox-precaching in prod builds.

I think it should be an explicit goal for V3 to aim to be 10KB in size (max of 15KB if we slip) and set that as a launch blocker. With that in mind, a pr-bot plugin that checks size from the get go would get a big 👍 from me.

Should we also explicitly track refreshing the Webpack plugin with @goldhand's input as part of the V3 work? Perhaps it's not strictly tied to the work here and just gets tracked as part of the same milestones.

**Comment by goldhand** [comment]
Some goals for webpack:

- [ ] Use compilation assets to generate a manifest (instead of globPatterns)
- [ ] Allow user to specify chunks to be used when creating the manifest
- [ ] Generate service worker “in-memory” and make webpack responsible for writing to file system
- [ ] Support sw-precache config in workbox-webpack plugin (runtime-caching? drop staticFileIgnores in favor of “chunks” api)

**Comment by gauntface** [comment]
I'm going to close this now since it's not serving much use anymore.
