### ISSUE TITLE
workbox-routing Meta Bug

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#991]
- [x] Workbox-SW Pieces Implemented
- [x] 100% Code Coverage
- [x] Demo
- [ ] API Docs Reviewed
- [x] Module Intro Written
- [x] Module Intro Reviewed
