### ISSUE TITLE
workbox-precaching Meta Bug

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#992]
- [x] Workbox-SW Pieces Implemented
- [x] 100% Code Coverage
- [x] Demo
- [x] API Docs Reviewed
- [x] Module Intro Written
