### ISSUE TITLE
workbox-runtime-caching Meta Bug

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#993]
- [x] Workbox-SW Pieces Implemented
- [x] 100% Code Coverage
- [x] Demo
- [ ] API Docs Reviewed
- [x] Module Intro Written
- [ ] Module Intro Reviewed
