### ISSUE TITLE
workbox-sw Meta Bug

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#995]
- [x] Workbox-SW Pieces Implemented
- [x] 100% Code Coverage
- [x] Demo
- [ ] API Docs Reviewed
- [x] Module guide Written
- [ ] Module guide reviewed
