### ISSUE TITLE
workbox-core Meta Bug

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#996]
- [x] Workbox-SW Pieces Implemented
- [x] 100% Code Coverage
- [x] Demo
- [x] API Docs Reviewed
- [x] Module Intro Written
