### ISSUE TITLE
Written Guides Meta Bug

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#997]
- [x] Getting Started: Written
- [x] Getting Started: Reviewed
- [x] Configure Workbox: Written
- [x] Configure Workbox: Reviewed
- [ ] How to precache files: Written
- [ ] How to precache files: Reviewed
- [x] How to Route Requests: Written
- [x] How to Route Requests: Reviewed
- [x] How to Handle Third Party Requests: Written
- [x] How to Handle Third Party Requests: Reviewed
- [x] Common Recipes for Workbox: Written
- [x] Common Recipes for Workbox: Reviewed
- [x] How to Troubleshoot and Debug: Written
- [x] How to Troubleshoot and Debug: Reviewed
